### ISSUE TITLE
New v8 Search / Filter box limits part discovery

### ISSUE THREAD

**Issue by nseidle** [sparkfun/SparkFun-KiCad-Libraries#71]
In v7, the searching the word 'SparkFun Push' allowed discovery of all SparkFun available push button switches because the search box included the file names ("SparkFun-Switch.pretty" was included). In v8, the file names are not searched, so only the FPs that have the word sparkfun explicitly in the keyword/description box is included in the search results.

I put 'SparkFun' in front of nearly all my searches to remove the kicad default libs, but this is hindering v8 use. This is a problem for symbol search as well.

Possible solutions:

* Add the keyword SparkFun to all FPs and symbols.
* Make users not import/use default KiCad libs/symbols, just search without the word SparkFun
* Allow import of default libraries, make user wade through 

@PaulZC I'm leaning towards adding the keyword but it feels brute force to me. Have you got any ideas?

![image](https://github.com/sparkfun/SparkFun-KiCad-Libraries/assets/117102/f8308eec-8821-44d6-86a2-1afd1962fa8f)

![image](https://github.com/sparkfun/SparkFun-KiCad-Libraries/assets/117102/e149a265-704c-4c11-a517-621763c92d92)

And symbols as well:
![image](https://github.com/sparkfun/SparkFun-KiCad-Libraries/assets/117102/8fc14b10-cf90-429c-a0be-941ec2228935)

**Comment by PaulZC** [comment]
@nseidle : are you on 8.0.0 or 8.0.1? I _think_ it is behaving correctly for me in 8.0.1? But my libraries are still in v7 format...

**Comment by nseidle** [comment]
Interesting. I'm on 8.0.1. I haven't converted or re-saved any lib (still in v7). I just did the standard adding of KiCad libraries to the end of the defaults:

![image](https://github.com/sparkfun/SparkFun-KiCad-Libraries/assets/117102/cc11f18f-5aa1-4027-8bd3-95b8d17e863d)

How are you installing things?

**Comment by PaulZC** [comment]
Here's what I see in 8.0.1:

In the schematic editor:

![image](https://github.com/sparkfun/SparkFun-KiCad-Libraries/assets/5690545/8085dabd-2827-4339-91d1-e86c3a59858b)

In the symbol editor:

![image](https://github.com/sparkfun/SparkFun-KiCad-Libraries/assets/5690545/543e62cc-562a-4235-8486-6a315b96d112)

Ah. Interesting. Searching for "sparkfun" doesn't find the PowerSymbol symbols. With no filter, it's there:

![image](https://github.com/sparkfun/SparkFun-KiCad-Libraries/assets/5690545/47d47bdf-6500-4680-b8cd-f8d4e803dba2)

Add "sparkfun" as the filter and it's not there:

![image](https://github.com/sparkfun/SparkFun-KiCad-Libraries/assets/5690545/e585a207-1edf-4e7a-8b23-c57e81d87e2d)

Everything goes weirdly non-alphabetic too:

![image](https://github.com/sparkfun/SparkFun-KiCad-Libraries/assets/5690545/48ea0c75-c8b8-40f2-9729-d58f67db97ca)

**Comment by PaulZC** [comment]
MicroMod is missing too. I think this only applies to MicroMod and PowerSymbols? Ah, MicroMod doesn't contain any symbols.

How am I installing things? With Preferences \ Manage Symbol Libraries. I use the folder button to add them all in one go:

![image](https://github.com/sparkfun/SparkFun-KiCad-Libraries/assets/5690545/38e8a5cb-d881-4fcf-a6d0-6fe8f9901fb2)

Same for the footprint editor. Preferences \ Manage Footprint Libraries and the folder button:

![image](https://github.com/sparkfun/SparkFun-KiCad-Libraries/assets/5690545/52f12e75-f200-4d64-a733-0c679a13e7e5)

Oh... Is it because PowerSymbols doesn't reference any SparkFun footprints? If it did, it would find them...

I'm with you on adding SparkFun to the Keywords. Sounds like a job for Reg Ex... Watch this space...

**Comment by PaulZC** [comment]
OK. That's better:

![image](https://github.com/sparkfun/SparkFun-KiCad-Libraries/assets/5690545/f9b46d71-9a11-412b-9af7-db673f6778aa)

PR is [here](https://github.com/sparkfun/SparkFun-KiCad-Libraries/pull/72)

**Comment by nseidle** [comment]
I added keywords to the footprints.
